const resorts = {
  "6": [
    {
      parentId: "6",
      resort_id: "21",
      id: "74",
      itemName: "Addo Rest Camp",
      category: "Addo Elephant National Park",
    },
    {
      parentId: "6",
      resort_id: "158",
      id: "257",
      itemName: "Langebos Huts",
      category: "Addo Elephant National Park",
    },
    {
      parentId: "6",
      resort_id: "161",
      id: "76",
      itemName: "Matyholweni Rest Camp",
      category: "Addo Elephant National Park",
    },
    {
      parentId: "6",
      resort_id: "263",
      id: "264",
      itemName: "Nyathi Rest Camp",
      category: "Addo Elephant National Park",
    },
    {
      parentId: "6",
      resort_id: "242",
      id: "130",
      itemName: "Spekboom Tented Rest Camp",
      category: "Addo Elephant National Park",
    },
  ],
  "7": [
    {
      parentId: "7",
      resort_id: "88",
      id: "223",
      itemName: "Agulhas Rest Camp",
      category: "Agulhas National Park",
    },
    {
      parentId: "7",
      resort_id: "258",
      id: "224",
      itemName: "Bergplaas Guest House",
      category: "Agulhas National Park",
    },
    {
      parentId: "7",
      resort_id: "257",
      id: "225",
      itemName: "Rhenosterkop Rest Camp",
      category: "Agulhas National Park",
    },
  ],
  "8": [
    {
      parentId: "8",
      resort_id: "27",
      id: "2779",
      itemName: "Augrabies Falls Rest Camp",
      category: "Augrabies Falls National Park",
    },
  ],
  "9": [
    {
      parentId: "9",
      resort_id: "22",
      id: "268",
      itemName: "Bontebok Rest Camp",
      category: "Bontebok National Park",
    },
  ],
  "10": [
    {
      parentId: "10",
      resort_id: "54",
      id: "63",
      itemName: "Glen Reenen Rest Camp",
      category: "Golden Gate Highlands National Park",
    },
    {
      parentId: "10",
      resort_id: "171",
      id: "92",
      itemName: "Highlands Mountain Retreat",
      category: "Golden Gate Highlands National Park",
    },
    {
      parentId: "10",
      resort_id: "261",
      id: "256",
      itemName: "Noord-Brabant",
      category: "Golden Gate Highlands National Park",
    },
  ],
  "11": [
    {
      parentId: "11",
      resort_id: "23",
      id: "269",
      itemName: "Karoo Rest Camp",
      category: "Karoo National Park",
    },
  ],
  "12": [
    {
      parentId: "12",
      resort_id: "52",
      id: "57",
      itemName: "Bitterpan Wilderness Camp",
      category: "Kgalagadi Transfrontier Park",
    },
    {
      parentId: "12",
      resort_id: "166",
      id: "89",
      itemName: "Gharagab Wilderness Camp",
      category: "Kgalagadi Transfrontier Park",
    },
    {
      parentId: "12",
      resort_id: "55",
      id: "58",
      itemName: "Grootkolk Wilderness Camp",
      category: "Kgalagadi Transfrontier Park",
    },
    {
      parentId: "12",
      resort_id: "56",
      id: "59",
      itemName: "Kalahari Tented Camp",
      category: "Kgalagadi Transfrontier Park",
    },
    {
      parentId: "12",
      resort_id: "164",
      id: "90",
      itemName: "Kieliekrankie Wilderness Camp",
      category: "Kgalagadi Transfrontier Park",
    },
    {
      parentId: "12",
      resort_id: "44",
      id: "55",
      itemName: "Mata-Mata Rest Camp",
      category: "Kgalagadi Transfrontier Park",
    },
    {
      parentId: "12",
      resort_id: "58",
      id: "56",
      itemName: "Nossob Rest Camp",
      category: "Kgalagadi Transfrontier Park",
    },
    {
      parentId: "12",
      resort_id: "57",
      id: "54",
      itemName: "Twee Rivieren Rest Camp",
      category: "Kgalagadi Transfrontier Park",
    },
    {
      parentId: "12",
      resort_id: "165",
      id: "91",
      itemName: "Urikaruus Wilderness Camp",
      category: "Kgalagadi Transfrontier Park",
    },
  ],
  "14": [
    {
      parentId: "14",
      resort_id: "90",
      id: "62",
      itemName: "Bontle Rest Camp",
      category: "Marakele National Park",
    },
    {
      parentId: "14",
      resort_id: "91",
      id: "60",
      itemName: "Tlopi Tented Camp",
      category: "Marakele National Park",
    },
  ],
  "15": [
    {
      parentId: "15",
      resort_id: "25",
      id: "15",
      itemName: "Mountain Zebra National Park",
      category: null,
    },
    {
      parentId: "15",
      resort_id: "25",
      id: "274",
      itemName: "Mountain Zebra Rest Camp",
      category: "Mountain Zebra National Park",
    },
  ],
  "16": [
    {
      parentId: "16",
      resort_id: "264",
      id: "265",
      itemName: "GroenRivier Coastal Rest Camp",
      category: "Namaqua National Park",
    },
    {
      parentId: "16",
      resort_id: "87",
      id: "109",
      itemName: "Skilpad Rest Camp ",
      category: "Namaqua National Park",
    },
  ],
  "17": [
    {
      parentId: "17",
      resort_id: "81",
      id: "83",
      itemName: "De Hoop Camping Site",
      category: "|Ai-|Ais/Richtersveld Transfrontier Park",
    },
    {
      parentId: "17",
      resort_id: "176",
      id: "97",
      itemName: "Gannakouriep Wilderness Camp",
      category: "|Ai-|Ais/Richtersveld Transfrontier Park",
    },
    {
      parentId: "17",
      resort_id: "83",
      id: "86",
      itemName: "Kokerboomkloof Camp Site",
      category: "|Ai-|Ais/Richtersveld Transfrontier Park",
    },
    {
      parentId: "17",
      resort_id: "84",
      id: "87",
      itemName: "Potjiespram Camp Site",
      category: "|Ai-|Ais/Richtersveld Transfrontier Park",
    },
    {
      parentId: "17",
      resort_id: "85",
      id: "88",
      itemName: "Richtersberg Camp Site",
      category: "|Ai-|Ais/Richtersveld Transfrontier Park",
    },
    {
      parentId: "17",
      resort_id: "33",
      id: "95",
      itemName: "Sendelingsdrif Rest Camp",
      category: "|Ai-|Ais/Richtersveld Transfrontier Park",
    },
    {
      parentId: "17",
      resort_id: "175",
      id: "101",
      itemName: "Tatasberg Wilderness Camp",
      category: "|Ai-|Ais/Richtersveld Transfrontier Park",
    },
  ],
  "19": [
    {
      parentId: "19",
      resort_id: "39",
      id: "108",
      itemName: "Cape Point ",
      category: "Table Mountain National Park",
    },
    {
      parentId: "19",
      resort_id: "178",
      id: "245",
      itemName: "Tented Camps And Overseers",
      category: "Table Mountain National Park",
    },
  ],
  "20": [
    {
      parentId: "20",
      resort_id: "256",
      id: "226",
      itemName: "Elandsberg Rest Camp",
      category: "Tankwa Karoo National Park",
    },
    {
      parentId: "20",
      resort_id: "86",
      id: "227",
      itemName: "Tankwa Karoo Rest Camp ",
      category: "Tankwa Karoo National Park",
    },
  ],
  "21": [
    {
      parentId: "21",
      resort_id: "204",
      id: "110",
      itemName: "Haak-en-Steek Camp",
      category: "Mokala National Park",
    },
    {
      parentId: "21",
      resort_id: "208",
      id: "129",
      itemName: "Lilydale Rest Camp",
      category: "Mokala National Park",
    },
    {
      parentId: "21",
      resort_id: "34",
      id: "111",
      itemName: "Mosu Lodge",
      category: "Mokala National Park",
    },
    {
      parentId: "21",
      resort_id: "246",
      id: "141",
      itemName: "Motswedi Camp Site",
      category: "Mokala National Park",
    },
  ],
  "22": [
    {
      parentId: "22",
      resort_id: "162",
      id: "71",
      itemName: "Leokwe Rest Camp",
      category: "Mapungubwe National Park",
    },
    {
      parentId: "22",
      resort_id: "163",
      id: "72",
      itemName: "Limpopo Forest Tented Camp",
      category: "Mapungubwe National Park",
    },
    {
      parentId: "22",
      resort_id: "205",
      id: "107",
      itemName: "Mazhou Camp Site",
      category: "Mapungubwe National Park",
    },
    {
      parentId: "22",
      resort_id: "89",
      id: "69",
      itemName: "Tshugulu Lodge",
      category: "Mapungubwe National Park",
    },
    {
      parentId: "22",
      resort_id: "167",
      id: "112",
      itemName: "Vhembe Wilderness Camp",
      category: "Mapungubwe National Park",
    },
  ],
  "23": [
    {
      parentId: "23",
      resort_id: "29",
      id: "23",
      itemName: "West Coast National Park",
      category: null,
    },
    {
      parentId: "23",
      resort_id: "29",
      id: "271",
      itemName: "West Coast Rest Camp",
      category: "West Coast National Park",
    },
  ],
  "26": [
    {
      parentId: "26",
      resort_id: "11",
      id: "239",
      itemName: "Balule Satellite Camp  ",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "6",
      id: "51",
      itemName: "Bateleur Bushveld Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "19",
      id: "31",
      itemName: "Berg-en-Dal Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "36",
      id: "32",
      itemName: "Biyamiti Bushveld Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "35",
      id: "52",
      itemName: "Boulders Bush Lodge",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "37",
      id: "81",
      itemName: "Crocodile Bridge Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "221",
      id: "123",
      itemName: "Hamiltons Tented Camp (Luxury Lodge)",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "8",
      id: "34",
      itemName: "Letaba Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "18",
      id: "35",
      itemName: "Lower Sabie Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "24",
      id: "48",
      itemName: "Malelane Satellite Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "15",
      id: "49",
      itemName: "Maroela Satellite Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "4",
      id: "36",
      itemName: "Mopani Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "9",
      id: "37",
      itemName: "Olifants Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "13",
      id: "38",
      itemName: "Orpen Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "259",
      id: "228",
      itemName: "Pafuri Border Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "20",
      id: "39",
      itemName: "Pretoriuskop Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "2",
      id: "40",
      itemName: "Punda Maria Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "245",
      id: "216",
      itemName: "Rhino Post Safari Lodge (Luxury Lodge)",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "79",
      id: "53",
      itemName: "Roodewal Bush Lodge",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "10",
      id: "41",
      itemName: "Satara Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "7",
      id: "42",
      itemName: "Shimuwini Bushveld Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "5",
      id: "43",
      itemName: "Shingwedzi Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "3",
      id: "44",
      itemName: "Sirheni Bushveld Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "17",
      id: "45",
      itemName: "Skukuza Rest Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "16",
      id: "46",
      itemName: "Talamati Bushveld Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "14",
      id: "50",
      itemName: "Tamboti Satellite Camp",
      category: "Kruger National Park",
    },
    {
      parentId: "26",
      resort_id: "183",
      id: "102",
      itemName: "Tsendze Rustic Camp Site",
      category: "Kruger National Park",
    },
  ],
  "94": [
    {
      parentId: "94",
      resort_id: "182",
      id: "273",
      itemName: "Camdeboo Rest Camp",
      category: "Camdeboo National Park",
    },
  ],
  "113": [
    {
      parentId: "113",
      resort_id: "93",
      id: "134",
      itemName: "Knysna Lakes Section",
      category: "Garden Route National Park",
    },
    {
      parentId: "113",
      resort_id: "50",
      id: "116",
      itemName: "Nature's Valley Rest Camp",
      category: "Garden Route National Park",
    },
    {
      parentId: "113",
      resort_id: "26",
      id: "115",
      itemName: "Storms River Mouth Rest Camp",
      category: "Garden Route National Park",
    },
    {
      parentId: "113",
      resort_id: "30",
      id: "117",
      itemName: "Wilderness Ebb-and-Flow Rest Camp",
      category: "Garden Route National Park",
    },
  ],
};
var result = [];
var i = 0;
for (const [key, value] of Object.entries(resorts)) {
  const namee = value[0].category || "null";
  //   console.log(key, " ksdfasdoifjs ", value);
  result.push({ id: key, name: namee, camp: [] });
  for (const [key2, value2] of Object.entries(value)) {
    result[i].camp.push({ id: value2.id, name: value2.itemName });
  }
  i++;
}

console.log(JSON.stringify(result, null, 2));
